### ISSUE TITLE
Replacing minikraken_20171019_4GB with minikraken2_v2_8GB_201904?

### ISSUE THREAD

**Issue by DrB-S** [DHQP/QuAISAR_singularity#2]
Is it possible to replace kraken with kraken2 (i.e., minikraken_20171019_4GB with minikraken2_v2_8GB_201904)?

**Comment by DrB-S** [comment]
What steps do I need to take to use python3.9.5 with QuAISAR? 
Especially in regards to replacing py36_biopython with py39_biopython.
Is py39_biopython.yml available?

**Comment by nvlachos** [comment]
Hello, 
   Thank you for the inquiries. Currently the public version of the pipeline only has the original kraken included. However, we have been utilizing kraken2 in the specialized version (specific paths and cluster access) of the pipeline we run. We do intend to include it in the public version, but there is no specific time frame as of yet. 
As far as updating the python and biopython versions, I will have to take a look into a few things to confirm before I can asnwer. What reason do you need it to use 3.9.5?

**Comment by DrB-S** [comment]
I have been using the original kraken version with your public release of QuAISAR_singularity (Qs) for several months for bacterial analyses at AZDHS in Phoenix.  I have downloaded Kraken2 and the 8MB database to our server, and I am not clear how to replace Kraken with Kraken2 and its db. 
  I have upgraded to python 3.9.5 on our server because of performance improvements, especially speed.
The Qs installation directory contains py36_biopython.yml and py36_biopython.txt.  
Can I modify py36_biopython.txt to use python 3.9.5 like this:
     conda create --name py36_biopython python=3.6 biopython -y
to
     conda create --name py39_biopython python=3.9.5 biopython -y

**Comment by DrB-S** [comment]
When I ran conda create for py39 as above, I received these error messages:
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
biopython -> python[version='2.7.*|3.5.*|3.6.*|3.4.*|**>=3.9,<3.10.0a0**|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
python=3.9.5
biopython -> mmtf-python -> python[version='3.10.*|3.9.*|3.8.*|3.7.*']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.26=0
  - feature:|@/linux-64::__glibc==2.26=0
  - biopython -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.26

**Comment by DrB-S** [comment]
Biopython is installed.
And "Everything is preinstalled and ready to run"
But lines 267 and 268 in quaisar_singularity.sh are failing:
   line 267: get_ratio: command not found
   line 268: get_ratio_Date: command not found
Those functions are present in get_latestDBs.sh

The pipeline is working now (removed the -r command-line argument!!).
I am still seeing the "command not found" messages for  lines 267 & 268.
